#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := baidu-tts

export ESP_SKR_PROJECT_PATH := $(realpath ../../)

export IDF_PATH := $(ESP_SKR_PROJECT_PATH)/esp-idf

include $(ESP_SKR_PROJECT_PATH)/component.mk

include $(IDF_PATH)/make/project.mk
